/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_allen_demo_jnidemo_JNIMethod */

#ifndef _Included_com_allen_demo_jnidemo_JNIMethod
#define _Included_com_allen_demo_jnidemo_JNIMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_allen_demo_jnidemo_JNIMethod
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_allen_demo_jnidemo_JNIMethod_sayHello
  (JNIEnv *env, jclass){
  return env->NewStringUTF((char *) "Hello! I'm from the JNI Method.");
  };

#ifdef __cplusplus
}
#endif
#endif
